<?php

namespace Database\Seeders;

use App\Models\DistrictStatistic;
use Illuminate\Database\Seeder;

class DistrictStatisticSeeder extends Seeder
{
    /**
     * Run the database seeds for 17 Districts (Data Rilis 2026).
     */
    public function run(): void
    {
        $districts = [
            [
                'code' => '3313010',
                'name' => 'Jatipuro',
                'capital_name' => 'Jatipuro',
                'area_sqkm' => 40.37,
                'population' => 33850,
                'density' => 838,
                'villages_count' => 10,
                'featured_sector' => 'Pertanian Padi, Palawija & Peternakan Sapi',
                'description' => 'Terletak di bagian selatan Karanganyar berbatasan dengan Wonogiri, sentra penghasil padi dan palawija.',
                'color_code' => '#10b981',
            ],
            [
                'code' => '3313020',
                'name' => 'Jatiyoso',
                'capital_name' => 'Jatiyoso',
                'area_sqkm' => 67.16,
                'population' => 39420,
                'density' => 587,
                'villages_count' => 9,
                'featured_sector' => 'Hortikultura Sayuran, Kopi & Perkebunan Teh',
                'description' => 'Kecamatan dataran tinggi di lereng Gunung Lawu dengan pemandangan alam asri dan produksi sayuran segar.',
                'color_code' => '#059669',
            ],
            [
                'code' => '3313030',
                'name' => 'Jumapolo',
                'capital_name' => 'Jumapolo',
                'area_sqkm' => 55.67,
                'population' => 42680,
                'density' => 767,
                'villages_count' => 12,
                'featured_sector' => 'Pertanian Padi, Jagung & Industri Kayu Olahan',
                'description' => 'Wilayah perbukitan dengan potensi kehutanan rakyat dan pertanian pangan.',
                'color_code' => '#34d399',
            ],
            [
                'code' => '3313040',
                'name' => 'Jumantono',
                'capital_name' => 'Genengan',
                'area_sqkm' => 53.55,
                'population' => 47350,
                'density' => 884,
                'villages_count' => 11,
                'featured_sector' => 'Perkebunan Buah Durian, Karet & Peternakan',
                'description' => 'Dikenal sebagai salah satu sentra penghasil durian lokal unggul dan komoditas karet di Karanganyar.',
                'color_code' => '#6ee7b7',
            ],
            [
                'code' => '3313050',
                'name' => 'Matesih',
                'capital_name' => 'Matesih',
                'area_sqkm' => 39.83,
                'population' => 44820,
                'density' => 1125,
                'villages_count' => 9,
                'featured_sector' => 'Wisata Ziarah Mangadeg/Giribangun, Kerajinan & Pertanian',
                'description' => 'Kecamatan bersejarah dengan makam raja-raja Mangkunegaran dan Presiden Soeharto di Astana Giribangun.',
                'color_code' => '#3b82f6',
            ],
            [
                'code' => '3313060',
                'name' => 'Tawangmangu',
                'capital_name' => 'Tawangmangu',
                'area_sqkm' => 70.03,
                'population' => 48250,
                'density' => 689,
                'villages_count' => 10,
                'featured_sector' => 'Pariwisata Alam (Grojogan Sewu), Perhotelan & Sayuran Segar',
                'description' => 'Ikon pariwisata utama Kabupaten Karanganyar dengan hawa sejuk, air terjun Grojogan Sewu, dan sentra agrowisata.',
                'color_code' => '#2563eb',
            ],
            [
                'code' => '3313070',
                'name' => 'Ngargoyoso',
                'capital_name' => 'Ngargoyoso',
                'area_sqkm' => 65.34,
                'population' => 36720,
                'density' => 562,
                'villages_count' => 9,
                'featured_sector' => 'Perkebunan Teh Kemuning, Agrowisata Candi Cetho & Sukuh',
                'description' => 'Sentra wisata kebun teh Kemuning dan peninggalan purbakala Candi Cetho serta Candi Sukuh.',
                'color_code' => '#1d4ed8',
            ],
            [
                'code' => '3313080',
                'name' => 'Karangpandan',
                'capital_name' => 'Karangpandan',
                'area_sqkm' => 34.11,
                'population' => 43910,
                'density' => 1287,
                'villages_count' => 11,
                'featured_sector' => 'Kuliner Wisata, Kerajinan Gerabah & Sentra Tanaman Hias',
                'description' => 'Gerbang utama menuju kawasan wisata lereng Lawu dengan kuliner khas dan jalur perdagangan strategis.',
                'color_code' => '#60a5fa',
            ],
            [
                'code' => '3313090',
                'name' => 'Karanganyar',
                'capital_name' => 'Bejen',
                'area_sqkm' => 43.03,
                'population' => 89650,
                'density' => 2083,
                'villages_count' => 12,
                'featured_sector' => 'Pusat Pemerintahan, Perdagangan, Jasa & Pendidikan',
                'description' => 'Pusat pemerintahan dan ekonomi perkotaan Kabupaten Karanganyar dengan fasilitas publik terlengkap.',
                'color_code' => '#6366f1',
            ],
            [
                'code' => '3313100',
                'name' => 'Tasikmadu',
                'capital_name' => 'Kaling',
                'area_sqkm' => 27.60,
                'population' => 66420,
                'density' => 2406,
                'villages_count' => 10,
                'featured_sector' => 'Agroindustri Gula (PG Tasikmadu), UMKM & Kuliner',
                'description' => 'Pusat agrowisata bersejarah Pabrik Gula Tasikmadu peninggalan KGPAA Mangkunegara IV dan sentra UMKM.',
                'color_code' => '#818cf8',
            ],
            [
                'code' => '3313110',
                'name' => 'Jaten',
                'capital_name' => 'Jaten',
                'area_sqkm' => 25.55,
                'population' => 87200,
                'density' => 3413,
                'villages_count' => 8,
                'featured_sector' => 'Kawasan Industri Tekstil/Manufaktur, Pemukiman & Jasa',
                'description' => 'Kawasan industri terbesar di Karanganyar dan wilayah penyangga utama Kota Surakarta (Solo).',
                'color_code' => '#4f46e5',
            ],
            [
                'code' => '3313120',
                'name' => 'Colomadu',
                'capital_name' => 'Paulan',
                'area_sqkm' => 15.64,
                'population' => 76850,
                'density' => 4914,
                'villages_count' => 11,
                'featured_sector' => 'Wisata Heritage De Tjolomadoe, Bisnis, Properti & Kuliner',
                'description' => 'Enklave strategis Karanganyar di barat Solo, dekat Bandara Adi Soemarmo dengan destinasi De Tjolomadoe.',
                'color_code' => '#4338ca',
            ],
            [
                'code' => '3313130',
                'name' => 'Gondangrejo',
                'capital_name' => 'Tuban',
                'area_sqkm' => 56.80,
                'population' => 85460,
                'density' => 1505,
                'villages_count' => 13,
                'featured_sector' => 'Situs Purbakala Sangiran (Klaster Dayu), Industri & Properti',
                'description' => 'Lokasi Klaster Dayu Museum Manusia Purba Sangiran (Situs Warisan Dunia UNESCO) dan kawasan berkembang.',
                'color_code' => '#f59e0b',
            ],
            [
                'code' => '3313140',
                'name' => 'Kebakkramat',
                'capital_name' => 'Kebak',
                'area_sqkm' => 36.46,
                'population' => 67180,
                'density' => 1843,
                'villages_count' => 10,
                'featured_sector' => 'Industri Manufaktur/Kimia, Pertanian & Logistik Jalur Utama',
                'description' => 'Kawasan industri strategis di jalur arteri Solo-Surabaya dan persimpangan Tol Trans Jawa.',
                'color_code' => '#d97706',
            ],
            [
                'code' => '3313150',
                'name' => 'Mojogedang',
                'capital_name' => 'Mojogedang',
                'area_sqkm' => 53.31,
                'population' => 69210,
                'density' => 1298,
                'villages_count' => 13,
                'featured_sector' => 'Perkebunan Karet Batujamus, Padi, Jagung & Peternakan',
                'description' => 'Sentra perkebunan karet Batujamus dan lumbung pangan padi/palawija bagian utara Karanganyar.',
                'color_code' => '#b45309',
            ],
            [
                'code' => '3313160',
                'name' => 'Kerjo',
                'capital_name' => 'Kwadungan',
                'area_sqkm' => 46.82,
                'population' => 37150,
                'density' => 793,
                'villages_count' => 10,
                'featured_sector' => 'Perkebunan Karet, Buah Durian & Waduk Gondang',
                'description' => 'Lokasi bendungan megah Waduk Gondang untuk irigasi dan daya tarik wisata air.',
                'color_code' => '#ec4899',
            ],
            [
                'code' => '3313170',
                'name' => 'Jenawi',
                'capital_name' => 'Jenawi',
                'area_sqkm' => 56.08,
                'population' => 26380,
                'density' => 470,
                'villages_count' => 9,
                'featured_sector' => 'Candi Kethek, Candi Cetho, Agrowisata Sayuran & Kopi',
                'description' => 'Kecamatan paling timur laut di lereng utara Lawu berbatasan dengan Sragen dan Ngawi, kaya panorama alam.',
                'color_code' => '#db2777',
            ],
        ];

        foreach ($districts as $d) {
            DistrictStatistic::updateOrCreate(
                ['code' => $d['code']],
                $d
            );
        }
    }
}

